content/primer.md

This one triggers me, people get it wrong all the time. This is our fault for not building cli apps beyond the dojo, but it's important nonetheless to remain clear about the fact that the dojo is just _a_ cli app, not the cli itself.

primer: necessary nuance about dojo

---

content/guides/additional/unit-tests.md

currently says "how to unit tests", changed to "writing unit tests"

fix grammar of unit test guide title

---

content/guides/core/app-school/3-imports-and-aliases.md
content/guides/core/app-school/intro.md
content/reference/arvo/clay/clay.md
content/reference/arvo/concepts/_index.md
content/reference/azimuth/azimuth-eth.md
content/reference/azimuth/azimuth.md
content/reference/azimuth/ecliptic.md
content/reference/azimuth/hd-wallet.md
content/reference/azimuth/l2/layer2.md
content/reference/azimuth/life-and-rift.md
content/reference/glossary/ames.md
content/reference/glossary/bridge.md
content/reference/glossary/chat.md
content/reference/glossary/clay.md
content/reference/glossary/desk.md
content/reference/glossary/hoon.md
content/reference/glossary/moon.md
content/reference/glossary/pier.md
content/reference/glossary/reset.md
content/reference/glossary/rollups.md
content/reference/glossary/ship.md
content/reference/glossary/sync.md
pages/guides/[[...slug]].js
pages/reference/[[...slug]].js

Correct backlinks to urbit.org.
(actually throughout, not just glossary)

Glossary fix

---

content/reference/hoon/basic.md

Reference to Chapter 2 should be to Chapter 4.

reference/hoon/basic: fix reference typo, add link

---

content/guides/core/hoon-school/E-types.md

Chart does not need to be closed with triple backtick, and the typo leads to some weirdness where the prose following the chart is merged into the subsequent code block.

hoon-school/E-types: remove erroneous triple-tic

---

content/guides/additional/software-distribution.md
content/guides/core/app-school-full-stack/8-desk.md
content/guides/core/app-school-full-stack/9-final.md
content/reference/arvo/reference/filesystem.md

Fix glob links.

---

content/reference/hoon/style.md

These changes attempt to clarify the language of the "A" and "B" level style requirements in the Hoon style guide. The new wording makes the following improvements:
1. Relaxes "B" requirements to old "A" naming requirements and restructures "A" to strictly build upon "B" (previously, a code could be "A" without being "B" if it omitted faces from obvious structures).
2. Replaces "symbol" with "face" to adhere more closely to Hoon terminology (where appropriate).
3. Applies the "formal comment" wording more uniformly.
Preview:
(Direct port of [urbit.org#1577](https://github.com/urbit/urbit.org/pull/1577))

pages: improve clarity of A/B style requirements

---

pages/community/events/index.js

Currently an edge case on urbit.org + dev.urbit.org is that multi-day events we're in the middle of don't get shown on the events page at all. Why? Because we do some date math to sort events into buckets, and multi-day events aren't in the future nor are they in the past. But looking at our current logic befuddles me:
```js
starts > DateTime.now() && ends < now
```
Does this even work? If it starts *after* now and ends *before* now, it's "now"?
Reversing this is more intuitive and displays our current event on this site:
```js
starts < DateTime.now() && ends > now
```
If it starts before now and ends after now, it's now.

events: support multi-day events as happening now

---

content/guides/core/hoon-school/B-syntax.md

hoon-school: fix typo in Syntax

---

content/guides/core/hoon-school/A-intro.md

It looks like this is intended to display as ` rather than \

fix tic escape

---

content/guides/core/hoon-school/J-stdlib-text.md

Previously the example code for string splitting was "off by one" (e.g., when splitting "this is a test", it would return ["this" "is" "a"]. This change welds the result list with the final word from the input tape in the recursive base case.
Before:
```
> +tapesplit `tape`"this is a test"
<<"this" "is" "a">>
```
After:
```
> +tapesplit `tape`"this is a test"
<<"this" "is" "a" "test">>
```
I think there's a more elegant base case (without the use of `weld`), but alas I am a novice hooner. Perhaps you have an idea on how to simplify it,  @sigilante.

j-stdlib-text: fix split string example

---

content/guides/core/hoon-school/J-stdlib-text.md

In the previous paragraph, the reader is instructed to save a generator as `add.hoon`. This updates the example to use `+add` to call it.

j-stdlib: update generator name to match instructions

---

content/guides/core/hoon-school/K-doors.md

Adding the additional gates as described [in this exercise](https://developers.urbit.org/guides/core/hoon-school/K-doors#exercise-display-cards=) was causing compilations of `playing-cards.hoon` to fail. Turns out that `:playing-cards` the reference is not necessary when it's an arm within the parent core.
*Before*
```
kiln: commit detected at %base (local)
: /~dev/base/133/lib/playing-cards/hoon
clay: read-at-aeon fail [desk=%base care=%a case=[%da p=~2022.7.17..06.29.42..01ad] path=/lib/playing-cards/hoon]
/sys/vane/clay/hoon:<[911 30].[911 50]>
/lib/playing-cards/hoon::[1 1].[109 3]>
/lib/playing-cards/hoon::[51 3].[52 27]>
/lib/playing-cards/hoon::[52 3].[52 27]>
/lib/playing-cards/hoon::[52 4].[52 24]>
%redo-match
/lib/playing-cards/hoon::[54 3].[108 5]>
%redo-match …
```

k-doors: remove extraneous `playing-cards` ref

---

content/guides/core/hoon-school/F-cores.md

The backticks of an aura were closing a markdown code block. (`(snoc `(list @ud)`~[1 2 3] 4)`). I changed them to double backticks so now they appear as they are supposed to (``(snoc `(list @ud)`~[1 2 3] 4)``).

Escape backticks properly

---

components/icons/dojo.js
components/icons/index.js
content/overview/_index.md
content/overview/azimuth.md
content/overview/dojo.md
content/overview/hoon.md
content/overview/nock.md
content/overview/vere.md
pages/overview/[[...slug]].js

changed shell to dojo for consistency in using urbit nomenclature as titles, and added icon.
this ordering seemed to make more sense, lmk if you think otherwise.

changed shell to dojo and re-ordered overview sections

---

pages/reference/[[...slug]].js

Searching for something that was a subheading on a page (like `jest`) would skip the tree navigation flow in the reference view because it was too specific for comparison. We remove all params / subanchors / ids / whatever you call `#this` when doing the comparison now.

reference: tree nav ignores subanchors

---

content/guides/core/app-school/3-imports-and-aliases.md

Remove reference to `ford` being its own vane, since it's now part of `clay`.

app-school: remove Ford reference

---

content/reference/arvo/behn/tasks.md

This tripped me up, as I thought the wires were strictly for my internal bookkeeping and not something others cared about (as opposed to paths).
Not sure how to phrase it in the best way (and I also don't know if this applies to other parts of the system than agents), but here's a suggestion.

Clarify: behn takes %rest and  %wait on same wire

---

content/reference/hoon/stdlib/2b.md

Currently, ++skim is summarized as "Suffix". I change this to "Filter" which should be familiar to any functional programming language enthusiasts

Fix summary of ++skim

---

content/guides/additional/strings.md
content/guides/core/app-school/4-lifecycle.md
content/guides/core/hoon-school/B-syntax.md
content/guides/core/hoon-school/D-gates.md
content/guides/core/hoon-school/F-cores.md
content/guides/core/hoon-school/H-libraries.md
content/guides/core/hoon-school/I-testing.md
content/guides/core/hoon-school/K-doors.md
content/guides/core/hoon-school/M-typecheck.md
content/guides/core/hoon-school/N-logic.md
content/guides/core/hoon-school/P-stdlib-io.md
content/guides/core/hoon-school/R-metals.md
content/reference/arvo/clay/scry.md
content/reference/hoon/hoon-errors.md
content/reference/hoon/irregular.md
content/reference/hoon/rune/buc.md
content/reference/hoon/rune/cen.md
content/reference/hoon/rune/dot.md
content/reference/hoon/rune/ket.md
content/reference/hoon/rune/tis.md
content/reference/hoon/rune/wut.md
content/reference/hoon/stdlib/2i.md
content/reference/hoon/stdlib/4g.md
lib/glossary.js

(dottis heading already has the id `-dottis`, so having `{% #-dottis %}` doesn't change it)

fix rune subheading links, replace `{% customFence %}` with code block, and remove redundant heading id

---

content/guides/core/hoon-school/B-syntax.md
package-lock.json
package.json
pages/_document.js
pages/blog/[slug].js
pages/community/opportunities.js
pages/community/support.js
pages/guides/[[...slug]].js
pages/overview/[[...slug]].js
pages/reference/[[...slug]].js
tailwind.config.js

Adds all appropriate scaffolding to support MathJax on developers.urbit.org and then adds the component to our Markdown renderer:
- Bumps foundation-design-system to 0.5.0
- Adds the MathJax import and sets its config in _document.js.
For an example, see the equation in "Making a decision" here:
https://developers-urbit-2z5afpdft-urbit.vercel.app/guides/core/hoon-school/B-syntax#making-a-decision
Due to the bump to 0.5.0, we also get deduplication of header IDs, which was an occasional bug when two of the same header were on a page, creating strange behaviour in the table of contents.
Feel free to try migrating equations in this PR and we can tweak it more, or merge at your leisure ...
Fixes #182

build: add math component

---

content/guides/core/hoon-school/G-trees.md

When you pretty print the structure `[[1 2] [3 4]]` it displays as `[[1 2] 3 4]` in dojo,  
rather than `[[[1 2] 3] 4]` which may be closer akin to the structure beneath this one:
```
[[[1 2] 3] 4]
/           \
[[1 2] 3]         4
/   \
[1 2]    3
/   \
1     2
```

Revise balanced leaves example

---

package-lock.json
package.json
pages/guides/[[...slug]].js
pages/overview/[[...slug]].js
pages/reference/[[...slug]].js

Fixes #131 
In foundation-design-system 0.5.2 I add a backwards-compatible flag to ask for `lastModified` when using `getPage()`; it responds with a date like `July 11, 2022` in string format.
On applicable pages, I refer to that stamp.

pages: show last modified on docs content

---

content/reference/runtime/jetting.md

The original link 404s. ~timluc-miptev has a similar document with a different filename in the same repo, and it's probably a suitable replacement for the old one.

jets: Update broken link to ~timluc-miptev's jets explainer

---

content/guides/core/hoon-school/G-trees.md

I may be misunderstanding, but it currently makes more sense to say an outer name obscures an inner one.

Inner faces are shadowed by outer names

---

content/reference/arvo/iris/iris.md

Link incorrectly pointed to eyre; this PR points it to iris.

iris/iris.md: fix API Reference link

---

content/guides/quickstart/chat-guide.md

Just going through the doc and saw these super minor frictions, feel free to close if not necessary
First line, i got this when executing because of a `json` dir with `response.hoon` in it, so changed it to do `-r`
```
$ cp mycomet/squad/mar/{bill*,hoon*,json*,kelvin*,mime*,noun*,ship*,txt*,docket-0*} hut/mar/ 
cp: mycomet/squad/mar/json is a directory (not copied).
```
Second line:
```
$ cp -r mycomet/squad/sur/{docket*, squad*} hut/sur/
zsh: parse error near `}'
```

Fix smol bugs in setup for chat-guide.md

---

content/guides/core/hoon-school/F-cores.md

Noticed what I think is a syntax error on one of the first examples in the core guide.

Syntax fix for core guide

---

content/blog/literals.md

We don't currently support $ delimited Math markdown, so for now you need to wrap them in blocks like this. I'll add an issue.

content/literals.md: workaround inline math

---

content/reference/azimuth/l2/roller-tutorial.md

I tried following [this](https://developers.urbit.org/reference/azimuth/l2/roller-tutorial) guide and couldn't get it to work. After talking to a Tlon engineer (José), I discovered that the roller endpoint URL needs to end with `/v1/roller`, which contradicts the guide.
Please note that I was not trying to point a local version of Bridge at the roller, but rather just `curl`ing to it. So the reviewer should verify that this PR's update of `REACT_APP_ROLLER_HOST` is correct.

Fix incomplete L2 roller URL

---

content/reference/glossary/udon.md

Documentation says Sail but means Udon. See web+urbitgraph://group/~bitbet-bolbel/urbit-community/graph/~darrux-landes/development/170141184505960789598451042477890600960

fix typo, Sail -> Udon

---

content/reference/arvo/clay/data-types.md
content/reference/arvo/clay/scry.md
content/reference/arvo/clay/tasks.md

- add new tasks tombstoning & app management tasks
- documented previously undocumented scry endpoints
- update & rejigger data types reference

update clay types, tasks and scry endpoints

---

content/guides/quickstart/chat-guide.md
content/guides/quickstart/groups-guide.md
content/guides/quickstart/voting-guide.md

WIP until final filenames/URLs are confirmed.
See https://github.com/urbit/urbit.org/pull/1943 for similar `urbit.org` changes.

Update binary links to pull from new runtime repo

---

content/guides/additional/cli-tutorial.md

As of some amount of time ago, starting an agent no longer auto-links it. So, we provide the user with the manual command for doing so.

cli tutorial: manually |link started agents

---

content/reference/runtime/nouns.md

As I work on the event log truncation project, I'm going to be referring to the documentation on [developers.urbit.org](https://developers.urbit.org) and updating them to reflect the new [urbit/vere](https://github.com/urbit/vere) repository. @mcevoypeter will you please take a look?

Update file paths of u3 symbol definitions to match urbit/vere repo

---

lib/buildGlossary.js

Resolves #289 
The issue started when [**this**](https://github.com/urbit/foundation-design-system/blob/c8d953a852b044fd6e4dd6dc8c478609412bc76e/src/components/ui/Search/Search.js#L57) line in the design system was changed to [**this**](https://github.com/urbit/foundation-design-system/blob/8a448320003c2c9254481fc0b2cefaf2be3b324b/src/components/ui/Search/Search.js#L49).
You don't have this issue on the others websites probably because they are using an older version (0.7.1) of the design system.

Fix anchor links

---

content/reference/hoon/rune/tis.md

The existing example doesn't compile because it contains
(add a b c)
There's a chance that I'm the one that wrote the broken example back in like 2017 but anyway, the example provided in this commit 1) compiles and 2) illustrates why we have these kinds of "inverted" runes.
The discussion also needed a fix:
> `=-` is just like `=+` but its subexpressions are reversed. `=-` looks
> better than `=+` when the expression you're pinning to the subject is much
> *larger* than the expression that uses it.
Resolves #317.

Correct discussion and example of `tishep`

---

content/reference/hoon/rune/cen.md

As seen in various gall agents, you can write `~(. core sample)` to produce a "pre-slammed" version of a door. This is basically not documented in the rune reference—hence the present commit.
Resolves #319.

Discussion of `censig` with first leg as `.`

---

content/reference/hoon/stdlib/3b.md

I also noticed that
```
> (san:rs -343)
.-343
```
while the doc says
```
> (san:rs -343)
.-3.43e2'
```
There are probably others but I didn't change these in this PR.
I also noticed `++toi:rs` "Rounds `a` to the nearest integer." but really produces the `floor`, or nearest integer towards `0`.
```
> (toi:rs .2.2)
[~ --2]
> (toi:rs .2.8)
[~ --2]
> (toi:rs .-2.8)
[~ -2]
> (toi:rs .-2.2)
[~ -2]
```
There are probably others but I didn't change these in this PR.

Correct signed/unsigned for parameters in stdlib 3b

---

content/guides/additional/remote-scry.md
content/guides/core/app-school/10-scry.md
content/reference/arvo/ames/data-types.md
content/reference/arvo/ames/tasks.md
content/reference/arvo/concepts/scry.md
content/reference/arvo/gall/data-types.md
content/reference/arvo/gall/scry.md
content/reference/glossary/remote-scry.md

this adds the remote scries guide from wicrum to additional guides. It also adds a glossary entry, ames tasks reference, gall scry reference (which we previously didn't have) and tweaks a few other things related to scries.
this should not be merged until remote scries go live
resolves #359

document remote scries & add gall scry reference

---

content/reference/arvo/eyre/scry.md

Looks like `bindings` was incorrectly copy-pasted from the previous `%bindings` section.

eyre: fix %connections scry description typo

---

content/reference/hoon/rune/cen.md

This fixes a typo where `p,q,r` are introduced as the arguments of `%~`, but `a,b,c` are used to refer to the arguments afterwards.

Fix typo in censig docs

---

content/reference/arvo/clay/marks/examples.md
content/reference/arvo/clay/marks/writing-marks.md

the /mar/csv.hoon mark was removed from base, so the conflict is now just /lib/csv/hoon. This renames the lib in the writing marks example to /lib/csv-utils.hoon so conflicts are entirely avoided.
resolves #288

fix csv example lib name conflict in marks guide

---

content/reference/arvo/gall/gall-api.md

gall: clarify empty fact path only works in on-watch

---

content/guides/quickstart/chat-guide.md

I found the instructions a little confusing because there are two `hut/` directories created (three if you count the `|mount %hut` desk):
```
mkdir -p hut/{app,sur,mar,lib}
```
and the one resulting from:
```
npx @urbit/create-landscape-app
```
But I got it to work by reading carefully and with the change in the PR.

Fix glob location in Build a Chat App

---

content/reference/glossary/kernel.md

The title of the Kernel page in the glossary is incorrectly labeled as "Kelvin versioning". This is probably a copy-paste error. This also means the Glossary sidebar has 2 entries named "Kelvin versioning".
This commit fixes this typo.

Typo in glossary title (Kelvin versioning -> Kernel)
