- content/community.page.md
A guy I was helping with troubleshooting was literally trying to join ~todo-todo/urbit-index, so I fixed it
> Fixed urbit index host

- components/BlogPreview.js
- pages/blog.js
- pages/blog/[slug].js
old layout was difficult to scan, this improves legibility
> updated blog post layout and post styling

- lib/constants.js
- package-lock.json
> build: bump foundation-design-system, tweak footer title

- content/blog/hsl-competition.md
- content/guides/additional/workbook/_index.md
- content/guides/additional/workbook/rhonda.md
- content/guides/additional/workbook/roman.md
- content/guides/core/hoon-school/G-trees.md
- content/guides/core/hoon-school/K-doors.md
- content/guides/core/hoon-school/Q-func.md
Adds the Hoon workbook and a blog post about the HSL Competition.
> Hoon workbook

- content/guides/core/app-school-full-stack/_index.md
Matches the side panel.  Untested.
> Fix 404s in App School II (Full-Stack) TOC

- components/Search.js
> search: parallelise with promise.all

- content/guides/core/hoon-school/H-libraries.md
Updating the label for `--` from "tistis" --> "hephep"
https://developers.urbit.org/reference/hoon/rune/terminators#---hephep=
> h-libs: tistis --> hephep

- components/Header.js
- components/Sidebar.js
> components/Sidebar: match docs sidebar on mobile to main sidebar

- content/guides/core/hoon-school/D-gates.md
> D-gates backtick rendering

- components/IndexCard.js
- pages/index.js
Fixes #57
Note: Our events so far don't have images, which makes card rendering kind of weird.
> index: split posts and events under "what's new"

- components/Search.js
- lib/cache.js
- pages/api/search.js
dev.urbit.org version of https://github.com/urbit/urbit.org/pull/1674
> search: index and search subheadings

- content/guides/core/hoon-school/E-types.md
There is a typo, bucwut is written as %? instead of $?
> Correct % into buc $

- pages/reference/[[...slug]].js
If you searched for a completely divergent part of the reference docs, the tree in the sidebar wouldn't unfold to show you where you were. We recomponentise the sidebar into a `SidebarContent` component that has a useEffect to set the tree's open state every time we navigate.
(I really should make a lot of this logic and these components core in FDS since this is a one-off for this Very Long Section that could just be universal.)
> reference: toggle entire tree on nav

- content/overview/arvo.md
> fix vane links in arvo overview

- content/guides/core/app-school-full-stack/6-react-setup.md
> add versions to npm package install instructions

- components/icons/index.js
- components/icons/ringsig.js
- components/icons/squad.js
- content/guides/quickstart/chat-guide.md
- content/guides/quickstart/groups-guide.md
- content/guides/quickstart/intro.md
- content/guides/quickstart/voting-guide.md
- pages/guides/[[...slug]].js
- pages/index.js
This adds a third lightning guide for a groups app called Squad, and rewrites the other two apps to use it. It also adds a short introduction page. 
p.s. leave this to me to merge so I can update the example code repo and the apps on ~pocwet at the same time
> Add groups app

- content/reference/arvo/threads/gall/stop-thread.md
> stop-thread: fix example spacing nit

- content/guides/core/hoon-school/B-syntax.md
- content/guides/core/hoon-school/D-gates.md
- content/guides/core/hoon-school/F-cores.md
<sup>~ more info in commit descriptions</sup>
> hoon school minor edits

- content/guides/core/hoon-school/M-typecheck.md
> hoon school 12: remove dottis section as it ignores types

- components/BlogPreview.js
- components/icons/azimuth.js
- components/icons/functional.js
- components/icons/interface.js
- pages/blog.js
- pages/community/directory.js
- pages/community/index.js
- pages/courses.js
- pages/index.js
- pages/overview/[[...slug]].js
fixes some react attributes not having correct name, and react lists (i.e. list of components via `.map()`) not having `key` attribute
> fix react warnings/errors

- content/guides/additional/client.md
- pages/guides/[[...slug]].js
As seen at Assembly 2022.
I've made some modest changes including serving all components directly from the ship.
I've personally run through all steps of this on a clean slate but it's worth a careful re-read and re-work as well.
> %flap tutorial

- content/guides/additional/threads/fundamentals.md
- content/guides/core/app-school/2-agent.md
- content/guides/core/hoon-school/K-doors.md
- content/guides/core/hoon-school/O-subject.md
- content/guides/core/hoon-school/R-metals.md
fixes https://github.com/urbit/developers.urbit.org/issues/172
> hoon/app school fixes/edits

- content/reference/arvo/clay/marks/examples.md
> tweak mark example to circumvent broken syntax highlighter

- content/guides/quickstart/chat-guide.md
- content/guides/quickstart/groups-guide.md
- content/guides/quickstart/voting-guide.md
This adds extensive comments to the code in the quickstart guides & also restructures them so the commentary is inline with the tutorial rather than a separate section at the bottom
> Quickstart guide restructure

- content/guides/core/hoon-school/K-doors.md
> Fix typo in K-Doors.md

- content/overview/dojo.md
Include threads, Dojo session crashes, and `?` type inspection.
> Document some more Dojo features.

- pages/guides/[[...slug]].js
- pages/overview/[[...slug]].js
- pages/reference/[[...slug]].js
> pages: fix edit page on github links

- content/reference/arvo/khan/_index.md
- content/reference/arvo/khan/example.md
- content/reference/arvo/khan/khan.md
- content/reference/arvo/khan/tasks.md
- content/reference/arvo/khan/types.md
- content/reference/glossary/khan.md
this only documents khan's internal interface at this stage
> add khan reference

- package-lock.json
- package.json
- pages/_app.js
This analytics work was after my time; I checked Vercel and we do have env variables set up for this project, and this is how urbit.org has it integrated, so this should "just work"? We can deploy and see.
Fixes #217
> app, pkg: adding matomo

- content/guides/additional/app-workbook/_index.md
- content/guides/additional/aqua.md
- content/guides/additional/cli-tutorial.md
- content/guides/additional/http-api-guide.md
- content/guides/additional/json-guide.md
- content/guides/additional/parsing.md
- content/guides/additional/sail.md
- content/guides/additional/software-distribution.md
- content/guides/additional/strings.md
- content/guides/additional/threads/_index.md
- content/guides/additional/unit-tests.md
- content/guides/additional/workbook/_index.md
- package-lock.json
- package.json
- pages/guides/[[...slug]].js
- Adds descriptions to additional guides as well as `_index` files for directories
- Makes all those pages (pages + `_index` pages of subdirectories) into cards on the guides page, sorts alphabetically
> guides: generate additional guide cards from metadata

- components/Meta.js
addresses https://github.com/urbit/developers.urbit.org/issues/44
> new card image and description

- content/guides/core/hoon-school/S-math.md
Wrote this for the video demo so may as well include it in the standard docs.
> Include date/time tutorial

- content/guides/additional/_index.md
- content/guides/additional/vases.md
- content/reference/glossary/vase.md
Notes on vases written by Ted. Mostly this just adds references to the document and some minor structural tweaks. Also added a glossary entry for vases.
> add vase guide and glossary entry

- content/guides/core/hoon-school/I-testing.md
- content/guides/core/hoon-school/_index.md
Clarify which parts of Hoon School must be covered to really get what's going on.
> Mark parts of Hoon School as optional.

- content/guides/core/environment.md
Per @ashelkovnykov's notes (and partly verbatim).
> Document local networking.

- content/reference/hoon/rune/_index.md
- content/reference/hoon/rune/bar.md
- content/reference/hoon/rune/buc.md
- content/reference/hoon/rune/cen.md
- content/reference/hoon/rune/col.md
- content/reference/hoon/rune/constants.md
- content/reference/hoon/rune/dot.md
- content/reference/hoon/rune/fas.md
- content/reference/hoon/rune/ket.md
- content/reference/hoon/rune/lus.md
- content/reference/hoon/rune/mic.md
- content/reference/hoon/rune/sig.md
- content/reference/hoon/rune/terminators.md
- content/reference/hoon/rune/tis.md
- content/reference/hoon/rune/wut.md
- content/reference/hoon/rune/zap.md
> Correct rune ordering.

- content/reference/nock/explanation.md
Derived from ~timluc-miptev's [Nock for Everyday Coders](https://blog.timlucmiptev.space/part2.html#10-replace-a-memory-slot) and ~niblux-malnus's [Nock10Tutorial](https://github.com/niblyx-malnus/Nock10Tutorial/blob/main/README.md).
> Add Nock 10 explanation

- content/reference/additional/mip.md
> add mip reference

- content/courses/asl.md
- content/courses/awl.md
- content/courses/csl.md
- content/courses/hsl.md
This adds descriptions and mailing list submission for the next two cohort class offerings we are planning in 2023.
> School redesign

- content/blog/dev-workflows.md
- content/guides/additional/http-api-guide.md
- content/guides/additional/software-distribution.md
- content/guides/core/environment.md
- content/reference/azimuth/advanced-azimuth-tools.md
- content/reference/runtime/jetting.md
> Update for urbit/vere repo.

- content/guides/core/environment.md
baby fixes to minor issues noted here: https://github.com/urbit/developers.urbit.org/issues/276
> Update references to zuse 416, remove %garden-dev

- content/guides/additional/app-workbook/_index.md
- content/guides/additional/app-workbook/dbug.md
> Add explainer for %dbug

- content/reference/hoon/rune/buc.md
> Add $+ buclus rune docs.

- content/guides/additional/cli-tutorial.md
Exactly what it says on the tin, that's all there's to it.
> cli-tutorial: remove stray tic

- content/guides/core/app-school-full-stack/6-react-setup.md
- content/guides/core/app-school-full-stack/7-app-logic.md
- content/guides/core/app-school-full-stack/8-desk.md
- content/guides/quickstart/chat-guide.md
Resolves #310 by making the following changes:
- [developers.urbit.org Issue](https://github.com/urbit/developers.urbit.org/issues/310)
- [doc-examples PR](https://github.com/urbit/docs-examples/pull/15) 
- [Grant Text](https://github.com/urbit/urbit.org/blob/master/content/grants/2023/urbit-react-docs.md)
> Modernize React Examples

- content/guides/core/app-school-full-stack/7-app-logic.md
These changes update the source refs for the "App School II: Full Stack" documentation to reflect [last-second fixes to the source](https://github.com/urbit/docs-examples/pull/15/commits/a77793f4912fea887cba8d5b4b015616537baf78) made in the corresponding [`doc-examples` pull request](https://github.com/urbit/docs-examples/pull/15).
- [developers.urbit.org Issue](https://github.com/urbit/developers.urbit.org/issues/310)
- [doc-examples PR](https://github.com/urbit/docs-examples/pull/15) 
- [Grant Text](https://github.com/urbit/urbit.org/blob/master/content/grants/2023/urbit-react-docs.md)
> Source Ref Update for "Modernize React Examples"

- content/reference/arvo/ames/scry.md
- content/reference/arvo/ames/tasks.md
> ames: document %snub task and /ax/snubbed scry

- content/guides/core/app-school-full-stack/8-desk.md
- content/guides/quickstart/chat-guide.md
- content/guides/quickstart/groups-guide.md
- content/guides/quickstart/voting-guide.md
atm they don't work cos of demonorepoisation
also bumps kelvin versions
resolves #303 #322
> update quickstart & fullstack desk setup instructions

- content/guides/additional/udon.md
> add udon guide

- content/reference/hoon/limbs/wing.md
> Document wing resolution.

- content/guides/additional/app-workbook/_index.md
- content/guides/additional/app-workbook/ahoy.md
- content/guides/additional/app-workbook/dbug.md
- content/guides/additional/app-workbook/feature.md
- content/guides/additional/app-workbook/flap.md
- content/guides/additional/app-workbook/rpn.md
- content/guides/additional/app-workbook/track7.md
Add a couple of tutorials to the App Workbook and change the naming pattern.
> Add CLI apps to App Workbook.

- content/reference/hoon/irregular.md
- content/reference/hoon/rune/ket.md
> Improve ketcol and com documentation.

- content/guides/additional/app-workbook/feature.md
- content/guides/additional/app-workbook/flap.md
- content/guides/additional/json-guide.md
- content/guides/core/app-school-full-stack/3-json.md
- content/reference/arvo/threads/http-api.md
- content/reference/hoon/zuse/2d_1-5.md
- content/reference/hoon/zuse/2d_6.md
- content/reference/hoon/zuse/2d_7.md
- content/reference/hoon/zuse/2e_2-3.md
don't merge until 413 OTA officially deployed
resolves #342
> update all en-json/de-json to en:json/de:json for %zuse 413

- content/reference/arvo/eyre/data-types.md
- content/reference/arvo/eyre/tasks.md
don't merge until zuse 413 deployed
> add %set-response task and cache-entry type to eyre ref for 413

- content/guides/additional/noun-channels.md
- content/reference/arvo/eyre/data-types.md
also update data types refs
merge once 413 deployed
> add short, low-level overview of eyre noun channels for 413

- content/guides/additional/generators.md
> Document agent generators a bit more.

- content/reference/arvo/clay/tasks.md
See discussion at https://github.com/urbit/urbit/issues/6619
> clay api: note only %sing works for remote ships

- content/guides/additional/remote-scry.md
add warning message about subscriber bug & lack of encryption
@joemfb can you please confirm this is our current recommendation re: https://github.com/urbit/urbit/pull/6617
> remote scries guide: add warning message

- content/reference/arvo/gall/data-types.md
> gall types ref: update bowl /w sky

- content/reference/arvo/clay/scry.md
> clay ref: correct %x scry description

- content/guides/additional/workbook/_index.md
- content/guides/additional/workbook/abc-blocks.md
- content/guides/additional/workbook/luhn-number.md
- content/guides/additional/workbook/water-towers.md
@sigilante If you have time, could you add some more comments on the structure and merits of people's submissions? What I have there is fairly bare bones. Thanks.
> Added hsl-23-1 coding challenges to Hoon Workbook

- content/reference/arvo/dill/data-types.md
- content/reference/arvo/dill/dill.md
- content/reference/arvo/dill/scry.md
- content/reference/arvo/dill/tasks.md
- update scries
- update and restructure tasks
- update data types
- update overview in lieu of dill now supporting multiple sessions
resolves #391
resolves #362
> dill: bring all reference docs up-to-date

- content/reference/arvo/_index.md
- content/reference/arvo/lick/_index.md
- content/reference/arvo/lick/examples.md
- content/reference/arvo/lick/lick.md
- content/reference/arvo/lick/scry.md
- content/reference/arvo/lick/tasks.md
- content/reference/glossary/arvo.md
- content/reference/glossary/lick.md
- content/reference/glossary/vane.md
I've added some documentation for the %lick vane. This probably needs a review and will need changes.
> %lick documentation

- content/guides/additional/workbook/abc-blocks.md
- content/guides/additional/workbook/luhn-number.md
- content/guides/additional/workbook/water-towers.md
Just added hoon formatting to the code on the most recent 3 coding challenges.
> added hoon formatting to workbook challenges

- content/courses/asl.md
- pages/hackathon.js
I fixed some typos and reworded parts of the App School Live signup page and Hackathon signup page. Please check and let me know if you approve of the changes.
> Updated page for ASL and Hackathon

- content/reference/arvo/clay/scry.md
> clay: add missing buc-x scries to scry ref

- content/reference/arvo/overview.md
- content/reference/arvo/tutorials/move-trace.md
- content/reference/hoon/stdlib/4b.md
- content/reference/hoon/stdlib/4l.md
- content/reference/hoon/stdlib/4m.md
- content/reference/hoon/stdlib/5a.md
> change old terminology span/odor

- content/reference/arvo/eyre/scry.md
> update eyre scry ref

- content/reference/arvo/jael/tasks.md
> update jael api ref

- content/reference/arvo/concepts/scry.md
> scries: warn about scrying in +on-load

- content/reference/arvo/khan/khan.md
- content/reference/arvo/khan/tasks.md
> khan: update api ref

- content/reference/arvo/clay/data-types.md
- content/reference/arvo/clay/scry.md
- content/reference/arvo/clay/tasks.md
> clay: update types ref

- content/guides/quickstart/chat-guide.md
- content/guides/quickstart/groups-guide.md
- content/guides/quickstart/voting-guide.md
> fix: typos

- content/reference/arvo/threads/_index.md
- content/reference/arvo/threads/overview.md
- content/reference/arvo/threads/strandio.md
> threads: document strandio

- content/reference/arvo/gall/scry.md
> fix gall %x vane scry return type

- content/guides/core/hoon-school/J-stdlib-text.md
- content/reference/hoon/auras.md
- content/reference/hoon/stdlib/2q.md
> clarify term/knot are not ASCII in general

- content/reference/additional/dist/_index.md
- content/reference/additional/docs-app/_index.md
- content/reference/additional/docs-app/file-format.md
- content/reference/additional/docs-app/index-file.md
- content/reference/additional/docs-app/overview.md
- content/reference/additional/docs-app/structure.md
> add docs app docs

- content/reference/arvo/lick/_index.md
- content/reference/arvo/lick/guide.md
- content/reference/arvo/lick/lick.md
Same as #410 but merge conflicts fixed.
> Add lick documentation
